### ISSUE TITLE
Strip colours from user input early in plugin chain

### ISSUE THREAD

**Issue by csauve** [csauve/gb-plugins-modacity#3]
To allow downstream regex to match, strip colours from messages and call `next()`

**Comment by Wunkolo** [comment]
Probably just as easy as making an "is-alpha" filter like C++ does but might be an issue with utf8 and japanese characters and such so just parsing escape codes and removing them should do:
https://modern.ircdocs.horse/formatting.html

**Comment by csauve** [comment]
Library used for adding colour to messages also has a function to stripe formatting and colours. This is now filtering messages for downstream modules, so hopefully works as expected.
